### ISSUE TITLE
Inconsistent documentation on auto-updates

### ISSUE THREAD

**Issue by pvillano** [linuxserver/docker-jackett#131]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Consistency between `readme.md`, itself, and `docker-jackett/root/etc/services.d/jackett/run`.

Probably removal of `AUTO_UPDATE` environment variable from `README.md` and `run`; ` --NoUpdates` always on

## Current Behavior

Inconsistent information regarding autoupdates on master branch

* Application Setup
  * "Disable autoupdates in the webui to prevent jackett crashing, *the image is refreshed when new versions are released*."
* Parameters
  * "`-e AUTO_UPDATE=true` | Allow Jackett to update inside of the container (currently recommended by Jackett and enabled by default)
* Updating Info
  * use docker pull as is standard practice, yo

In the development branch,

1. the documentation for the auto-update environment variable is removed from readme.md,
1. but `docker-jackett/root/etc/services.d/jackett/run` still reads the environment variable
1. and defaults to auto-updating
1. and recommends disabling auto-updates in the web ui
1. and has the standard post-amble about how you should just update the container

## Alternatives Considered

going outside for a bit

**Comment by aptalca** [comment]
We usually don't allow updating inside the container unless it is absolutely necessary (ie. nextcloud, plex beta, etc.). Jackett for a long time did not allow updates inside the container. But then the upstream dev requested and insisted we add it because it made it easier for their support team. So we did. The readme on the master branch is accurate. It seems we neglected to update the readme on the develop branch when we added that functionality in.
