### ISSUE TITLE
[Code Fix] Missing opening brackets in external_trigger.yml

### ISSUE THREAD

**Issue by ilike2burnthing** [linuxserver/docker-jackett#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Per PR instructions I'm opening this as an issue, as it appears to just be a typo.

https://github.com/linuxserver/docker-jackett/blob/master/.github/workflows/external_trigger.yml#L93

```diff
-               if "${artifacts_found}" == "true" ]]; then
+               if [[ "${artifacts_found}" == "true" ]]; then
```

Introduced in https://github.com/linuxserver/docker-jackett/commit/c406221e8fee7eb2bd8217f44aff767334597a38, was causing the error `line 77: : command not found` in the step `External Trigger`:
- before - https://github.com/linuxserver/docker-jackett/actions/runs/11065859886/job/30746009747
- after - https://github.com/linuxserver/docker-jackett/actions/runs/11081866509/job/30794132191

**Comment by aptalca** [comment]
Yeah, this is a typo in our jenkins builder template, but it only affects a log message and doesn't fail the trigger. That's why we didn't notice it before.

https://github.com/linuxserver/docker-jenkins-builder/blob/master/roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2#L185

Thanks for the heads up.
